### ISSUE TITLE
How to run as dataflow template 

### ISSUE THREAD

**Issue by RokshanJ** [GoogleCloudPlatform/healthcare-data-harmonization-dataflow#3]
@lastomato 

Can we run this as a dataflow template?

I would like to store the dataflow template in GCS and then lunch the dataflow template in a batch manner. Is this possible to do ?

**Comment by lastomato** [comment]
At this moment, you will have to build the template, please see: https://cloud.google.com/dataflow/docs/guides/templates/overview for instructions. We will publish prebuilt templates at some point, but there is no ETA yet.
